### ISSUE TITLE
Mental Command

### ISSUE THREAD

**Issue by floriangamillscheg** [Emotiv/unity-plugin#8] opened 2021-05-06 09:38 UTC
Hey,

I want to use the mental commands for my application using Unity... I subscribe to sys and com data streams and then I load my profile.... But how am I able to retrieve the current mental commands? I can't find a method in DataStreamManager.... I know that the current command is printed in OnMentalCommandReceived but how can I actually get to the commands?

The commands that I get seem very random.... Usually when I start the EmotivBCI App, it sometimes asks me to relax (I guess to get my current neutral mental command) with my eyes open and then with my eyes closed... Is there a way in Unity to do the same? And could it be that when I get the mental commands in unity that it doesn't actually use the profile as its basis?

**Comment by bchaperon** [comment] 2021-06-02 05:32
Duplicate of https://github.com/Emotiv/cortex-v2-example/issues/139

**Closed by bchaperon** 2021-06-02 05:32 UTC
